#
# MSTAR touchpanel driver
#
obj-$(CONFIG_TOUCHSCREEN_MSG22XX)       += mstar_drv_common.o \
                                           mstar_drv_ic_fw_porting_layer.o \
                                           mstar_drv_main.o \
                                           mstar_drv_platform_interface.o \
                                           mstar_drv_platform_porting_layer.o \
                                           mstar_drv_qcom.o \
                                           mstar_drv_self_fw_control.o \
                                           mstar_drv_self_mp_test.o \
                                           mstar_drv_utility_adaption.o

